version: '3'

services:
  # Base image for all microservices
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: hotel-reservation-base:latest
    privileged: true
    user: "0"

  frontend:
    build: 
      context: .
      dockerfile: services/frontend_service/Dockerfile
    ports:
      - "50050:50050"
    networks:
      - hotel_network
    depends_on:
      - base
    privileged: true
    user: "0"
    volumes:
      - sockets:/tmp
      - logs:/logs

  search:
    build: 
      context: .
      dockerfile: services/search_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base
    privileged: true
    user: "0"
    volumes:
      - sockets:/tmp
      - logs:/logs

  profile:
    build: 
      context: .
      dockerfile: services/profile_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base
    privileged: true
    user: "0"
    volumes:
      - sockets:/tmp
      - logs:/logs

  recommendation:
    build: 
      context: .
      dockerfile: services/recommendation_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base
    privileged: true
    user: "0"
    volumes:
      - sockets:/tmp
      - logs:/logs

  user:
    build: 
      context: .
      dockerfile: services/user_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base
    privileged: true
    user: "0"
    volumes:
      - sockets:/tmp
      - logs:/logs

  reservation:
    build: 
      context: .
      dockerfile: services/reservation_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base
    privileged: true
    user: "0"
    volumes:
      - sockets:/tmp
      - logs:/logs

  rate:
    build: 
      context: .
      dockerfile: services/rate_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base
    privileged: true
    user: "0"
    volumes:
      - sockets:/tmp
      - logs:/logs

  geo:
    build: 
      context: .
      dockerfile: services/geo_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base
    privileged: true
    user: "0"
    volumes:
      - sockets:/tmp
      - logs:/logs

networks:
  hotel_network:
    driver: bridge 

volumes:
  sockets: 
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs 