version: '3'

services:
  # Base image for all microservices
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: hotel-reservation-base:latest
  frontend:
    build: 
      context: .
      dockerfile: frontend_service/Dockerfile
    ports:
      - "50050:50050"
    networks:
      - hotel_network
    depends_on:
      - base

  search:
    build: 
      context: .
      dockerfile: search_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base

  profile:
    build: 
      context: .
      dockerfile: profile_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base

  recommendation:
    build: 
      context: .
      dockerfile: recommendation_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base

  user:
    build: 
      context: .
      dockerfile: user_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base

  reservation:
    build: 
      context: .
      dockerfile: reservation_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base

  rate:
    build: 
      context: .
      dockerfile: rate_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base

  geo:
    build: 
      context: .
      dockerfile: geo_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base

networks:
  hotel_network:
    driver: bridge 