version: '3'

services:
  frontend:
    build: 
      context: .
      dockerfile: frontend_service/Dockerfile
    ports:
      - "50050:50050"
    networks:
      - hotel_network

  search:
    build: 
      context: .
      dockerfile: search_service/Dockerfile
    networks:
      - hotel_network

  profile:
    build: 
      context: .
      dockerfile: profile_service/Dockerfile
    networks:
      - hotel_network

  recommendation:
    build: 
      context: .
      dockerfile: recommendation_service/Dockerfile
    networks:
      - hotel_network

  user:
    build: 
      context: .
      dockerfile: user_service/Dockerfile
    networks:
      - hotel_network

  reservation:
    build: 
      context: .
      dockerfile: reservation_service/Dockerfile
    networks:
      - hotel_network

  rate:
    build: 
      context: .
      dockerfile: rate_service/Dockerfile
    networks:
      - hotel_network

  geo:
    build: 
      context: .
      dockerfile: geo_service/Dockerfile
    networks:
      - hotel_network

networks:
  hotel_network:
    driver: bridge 