version: '3'

services:
  # Base image for all microservices
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: hotel-reservation-base:latest
    privileged: true
    user: "0"

  frontend:
    build: 
      context: .
      dockerfile: frontend_service/Dockerfile
    ports:
      - "50050:50050"
    networks:
      - hotel_network
    depends_on:
      - base
    privileged: true
    user: "0"

  search:
    build: 
      context: .
      dockerfile: search_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base
    privileged: true
    user: "0"

  profile:
    build: 
      context: .
      dockerfile: profile_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base
    privileged: true
    user: "0"

  recommendation:
    build: 
      context: .
      dockerfile: recommendation_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base
    privileged: true
    user: "0"

  user:
    build: 
      context: .
      dockerfile: user_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base
    privileged: true
    user: "0"

  reservation:
    build: 
      context: .
      dockerfile: reservation_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base
    privileged: true
    user: "0"

  rate:
    build: 
      context: .
      dockerfile: rate_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base
    privileged: true
    user: "0"

  geo:
    build: 
      context: .
      dockerfile: geo_service/Dockerfile
    networks:
      - hotel_network
    depends_on:
      - base
    privileged: true
    user: "0"

networks:
  hotel_network:
    driver: bridge 